/* eslint-disable max-len */
export default [
  {
    index: 0,
    Day: '9.18',
    Time: '12:00 -14:00',
    Location: 'Princesa V',
    eCategory: 'Extended Council meeting',
    eID: undefined,
    eTitle:
      'IRPS council, executive body and RegPep2020 Program Committee meeting',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 1,
    Day: '9.18',
    Time: '14:00 - 17:00',
    Location: 'Atlantes Anfitreater',
    eCategory: 'Plenary Symposium',
    eID: 'PS',
    eTitle: 'Current topics in regulatory peptide research',
    firstName: 'Gareth',
    lastName: 'Leng',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'Gareth.Leng@ed.ac.uk ',
    state: 'Edinburgh',
    Country: 'UK',
    Institute: 'Centre for dicovery Brain Sciences,The University of Edinburgh',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 2,
    Day: '9.18',
    Time: '14:00 - 17:00',
    Location: 'Atlantes Anfitreater',
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Javier',
    lastName: 'Stern',
    Role: 'Speaker',
    talkTitle: 'Real-time two-photon imaging of the rat hypothalamus in vivo',
    Email: 'jstern@gru.edu',
    state: 'Atlanta',
    Country: 'USA',
    Institute: 'Georgia State University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 3,
    Day: '9.18',
    Time: '14:00 - 17:00',
    Location: 'Atlantes Anfitreater',
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Patrick',
    lastName: 'Sexton',
    Role: 'Speaker',
    talkTitle: 'Mechanisms of signalling in G protein-coupled receptors.',
    Email: 'patrick.Sexton@monash.edu',
    state: 'Melbourn',
    Country: 'Australia',
    Institute: 'Monash University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 4,
    Day: '9.18',
    Time: '14:00 - 17:00',
    Location: 'Atlantes Anfitreater',
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Andries',
    lastName: 'Kalsbeek',
    Role: 'Speaker',
    talkTitle: 'Circadian Homeostasis, driven by peptides of the central clock',
    Email: 'a.kalsbeek@nin.knaw.nl',
    state: 'Amsterdam',
    Country: 'Netherlands',
    Institute: 'The Netherlands Institute for Neuroscience',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 5,
    Day: '9.18',
    Time: '14:00 - 17:00',
    Location: 'Atlantes Anfitreater',
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Peng',
    lastName: 'Li',
    Role: 'Speaker',
    talkTitle: 'The peptidergic control circuit for sighing',
    Email: 'penglium@umich.edu ',
    state: 'Ann Arbor',
    Country: 'USA',
    Institute: 'The University of Michigan',
    professionalRole: 'Assistant Professor',
    Observation: undefined
  },
  {
    index: 6,
    Day: '9.18',
    Time: '14:00 - 17:00',
    Location: 'Atlantes Anfitreater',
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Luis',
    lastName: 'De Lecea',
    Role: 'Speaker',
    talkTitle:
      'Optogenetic control of neuromodulatory circuits in brain states',
    Email: 'hypocretin@gmail.com',
    state: 'Stanford',
    Country: 'USA',
    Institute: 'Stanford University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 7,
    Day: '9.18',
    Time: '14:00 - 17:00',
    Location: 'Atlantes Anfitreater',
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Marisela',
    lastName: 'Morales',
    Role: 'Speaker',
    talkTitle: 'Fast and slow co-transmission in the modulatory system',
    Email: 'mmorales@intra.nida.nih.gov',
    state: 'Baltimore',
    Country: 'USA',
    Institute: 'NIDA-IRP, NIH',
    professionalRole: 'Brand chief',
    Observation: undefined
  },
  {
    index: 8,
    Day: '9.18',
    Time: '17:00 - 19:00',
    Location: 'Atlantes Anfitreater',
    eCategory: 'Opening Ceremony',
    eID: undefined,
    eTitle: 'Lay Lecture',
    firstName: 'Ra\u00fal',
    lastName: 'Mart\u00edn del Campo',
    Role: 'speaker',
    talkTitle:
      'Opioids from an international policy point of view: from their \tavailability to the prevention of their abuse',
    Email: 'aulmc.incb@gmail.com ',
    state: 'Mexico',
    Country: 'Mexico',
    Institute:
      'The International Narcotics Control Board-INCB, United Nations and National Comission against Addiction',
    professionalRole: 'Director General',
    Observation: undefined
  },
  {
    index: 9,
    Day: '9.18',
    Time: '19:00 - 22:00',
    Location: 'Ocean hall/Pool area',
    eCategory: 'Welcome Reception',
    eID: undefined,
    eTitle: undefined,
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 11,
    Day: '9.19',
    Time: '8:30 - 9:30',
    Location: 'Atlantes Anfitreater',
    eCategory: 'Plenary',
    eID: 'PL2',
    eTitle: 'Plenary lecture 1',
    firstName: 'Carmen',
    lastName: 'Sandi',
    Role: 'Speaker',
    talkTitle: 'Neural circuits linking stress, anxiety and motivation',
    Email: 'carmen.sandi@epfl.ch',
    state: 'Lausanne',
    Country: 'Switzerland',
    Institute:
      'Brain and Mind Institute Swiss Federal Institute of Technology Lausanne (EPFL) and Federation of European Neuroscience Societies',
    professionalRole: 'Director and Presidente',
    Observation: undefined
  },
  {
    index: 12,
    Day: '9.19',
    Time: '9:45 - 10:45',
    Location: 'Atlantes Anfitreater',
    eCategory: 'Datablitz presentation',
    eID: undefined,
    eTitle: 'Selected poster presentaters - travel awardees',
    firstName: 'Ruud',
    lastName: 'Buijs',
    Role: 'Chair',
    talkTitle: 'Chair of RegPep2020',
    Email: 'ruudbuijs@gmail.com',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'Instituto de Investigaciones Biom\u00e9dicas, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 13,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa Rooms',
    eCategory: 'Concurent Symposia (CS)',
    eID: 'CS1',
    eTitle: 'Block 1',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 14,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa I',
    eCategory: 'CS block 1',
    eID: '1-A',
    eTitle: 'Oxytocin in energy balance ',
    firstName: 'Pawel',
    lastName: 'Olszewski',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'pawel@waikato.ac.nz',
    state: 'Hamilton',
    Country: 'New Zealand',
    Institute: 'Waikato University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 15,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa I',
    eCategory: 'CS block 1',
    eID: undefined,
    eTitle: ' ',
    firstName: 'James',
    lastName: 'Blevings',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'jeblevin@uw.edu',
    state: 'Seatle',
    Country: 'USA',
    Institute: 'University of Washington',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 16,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa I',
    eCategory: 'CS block 1',
    eID: '1-A-1',
    eTitle: undefined,
    firstName: 'Pawel',
    lastName: 'Olszewski',
    Role: 'Speaker',
    talkTitle: 'Oxytocin as a pharmacological tool to regulate meal size',
    Email: 'pawel@waikato.ac.nz',
    state: 'Hamilton',
    Country: 'New Zealand',
    Institute: 'Waikato University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 17,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa I',
    eCategory: 'CS block 1',
    eID: '1-A-2',
    eTitle: undefined,
    firstName: 'Margarita',
    lastName: 'Curras-Collazo',
    Role: 'Speaker',
    talkTitle:
      'Dysregulation of hypothalamic gene expression and the oxytocin system by diabetogenic soybean oil diets in mice',
    Email: 'mcur@ucr.edu',
    state: 'Riverside',
    Country: 'USA',
    Institute: 'UC Riverside',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 18,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa I',
    eCategory: 'CS block 1',
    eID: '1-A-3',
    eTitle: undefined,
    firstName: 'Emily',
    lastName: 'Noble',
    Role: 'Speaker',
    talkTitle: 'Central oxytocin in social and reward-based feeding',
    Email: 'Emily.Noble@uga.edu',
    state: 'Athens',
    Country: 'USA',
    Institute: 'University of Georgia',
    professionalRole: 'Assistent Professor',
    Observation: undefined
  },
  {
    index: 19,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa I',
    eCategory: 'CS block 1',
    eID: '1-A-4',
    eTitle: undefined,
    firstName: 'James',
    lastName: 'Blevings',
    Role: 'Speaker',
    talkTitle:
      'Use of oxytocin as a therapeutic strategy to treat obesity in diet-induced obese rodents and nonhuman primates',
    Email: 'jeblevin@uw.edu',
    state: 'Seatle',
    Country: 'USA',
    Institute: 'University of Washington',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 20,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa II',
    eCategory: 'CS block 1',
    eID: '1-B',
    eTitle:
      'The effect of exogenous neuropeptides on central signaling and behavior',
    firstName: 'Mary',
    lastName: 'Lee',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'leemary@mail.nih.gov',
    state: 'Bethesda',
    Country: 'USA',
    Institute: 'NIAAA',
    professionalRole: 'Researcher',
    Observation: undefined
  },
  {
    index: 21,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa II',
    eCategory: 'CS block 1',
    eID: '1-B-1',
    eTitle: undefined,
    firstName: 'Mary',
    lastName: 'Lee',
    Role: 'Speaker',
    talkTitle:
      'Evidence of central signaling after systemic administration of oxytocin',
    Email: 'leemary@mail.nih.gov',
    state: 'Bethesda',
    Country: 'USA',
    Institute: 'NIAAA',
    professionalRole: 'Researcher',
    Observation: undefined
  },
  {
    index: 22,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa II',
    eCategory: 'CS block 1',
    eID: '1-B-2',
    eTitle: undefined,
    firstName: 'Nina',
    lastName: 'Mash',
    Role: 'Speaker',
    talkTitle:
      'The role of oxytocin in modulating empathic altruism within and between social groups',
    Email: 'ninamarsh@me.com',
    state: 'Bad Zwischenahn',
    Country: 'Germany',
    Institute: 'Car von Ossietzky University Oldenburg ',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 23,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa II',
    eCategory: 'CS block 1',
    eID: '1-B-3',
    eTitle: undefined,
    firstName: 'Rene',
    lastName: 'Hurlemann ',
    Role: 'Speaker',
    talkTitle:
      'A novel therapeutic target for anxiety and posttraumatic stress disorders',
    Email: 'r.hurlemann@gmail.com',
    state: 'Bad Zwischenahn',
    Country: 'Germany',
    Institute: 'Car von Ossietzky University Oldenburg ',
    professionalRole: 'Professor',
    Observation: 'Chairing the RegPep2022'
  },
  {
    index: 24,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa II',
    eCategory: 'CS block 1',
    eID: '1-B-4',
    eTitle: undefined,
    firstName: 'Andreas',
    lastName: 'Schatzlein',
    Role: 'Speaker',
    talkTitle:
      'Molecular envelope technology (MET) for the delivery of therapeutic peptides to the brain',
    Email: 'a.schatzlein@ucl.ac.uk',
    state: 'London',
    Country: 'UK',
    Institute: 'School of Pharmarcy, UCL',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 25,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa III',
    eCategory: 'CS block 1',
    eID: '1-C',
    eTitle:
      'Neuroanatomy of brain peptidergic circuits: contribution to cognition and behavior',
    firstName: 'Limei',
    lastName: 'Zhang',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'limei@unam.mx',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'School of Medicine, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 26,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa III',
    eCategory: 'CS block 1',
    eID: '1-C-1',
    eTitle: undefined,
    firstName: 'Lee E.',
    lastName: 'Eiden',
    Role: 'Speaker',
    talkTitle:
      'VGLUT-VGAT co-expression in PACAP/PAC1 signaling delineates multisensory-cognitive-locomotor controlling circuits',
    Email: 'eidenl@mail.nih.gov',
    state: 'Bethesda',
    Country: 'USA',
    Institute: 'SMN, NIMH, NIH',
    professionalRole: 'Section Chief',
    Observation: undefined
  },
  {
    index: 27,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa III',
    eCategory: 'CS block 1',
    eID: '1-C-2',
    eTitle: undefined,
    firstName: 'Limei',
    lastName: 'Zhang',
    Role: 'Speaker',
    talkTitle:
      'Hindbrain to extended amygdala HiFi circuits modulate medial and lateral preoptic hypothalamus for defensive locomotion',
    Email: 'limei@unam.mx',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'School of Medicine, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 28,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa III',
    eCategory: 'CS block 1',
    eID: '1-C-3',
    eTitle: undefined,
    firstName: 'Nicholas ',
    lastName: 'Betley',
    Role: 'Speaker',
    talkTitle:
      'Peptidergic signaling in a hypothalamic to hindbrain circuit prioritizes hunger over pain',
    Email: 'jnbetley@sas.upenn.edu',
    state: 'Philadelphia',
    Country: 'USA',
    Institute: 'Department of Biology, UPenn',
    professionalRole: 'Assistent Professor',
    Observation: undefined
  },
  {
    index: 29,
    Day: '9.19',
    Time: '12:30 - 12:45',
    Location: 'Princesa III',
    eCategory: 'CS block 1',
    eID: '1-C-4',
    eTitle: undefined,
    firstName: 'Peter ',
    lastName: 'Duncan',
    Role: 'Speaker',
    talkTitle:
      'Corticotroph plasticity in stress: at the brain-endocrine  interface',
    Email: 'pduncan2@exseed.ed.ac.uk ',
    state: 'Edinburgh',
    Country: 'UK',
    Institute: 'Centre for dicovery Brain Sciences,The University of Edinburgh',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 30,
    Day: '9.19',
    Time: '12:45 - 13:00',
    Location: 'Princesa III',
    eCategory: 'CS block 1',
    eID: '1-C-5',
    eTitle: undefined,
    firstName: 'Rosie',
    lastName: 'Brown',
    Role: 'Speaker',
    talkTitle:
      'Prolactin action in the medial preoptic area is necessary for postpartum maternal nursing behavior',
    Email: 'rosemary.brown@otago.ac.nz',
    state: 'Dunedin',
    Country: 'UK',
    Institute: 'University of Otago',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 31,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 1',
    eID: '1-D',
    eTitle: 'Chromogranins and vascular, immune, and metabolic regulation',
    firstName: 'Sushil',
    lastName: 'Mahata',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'smahata@ucsd.edu ',
    state: 'San Diego',
    Country: 'USA',
    Institute: 'UCSU',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 32,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 1',
    eID: '1-D-1',
    eTitle: undefined,
    firstName: 'Sushil',
    lastName: 'Mahata',
    Role: 'Speaker',
    talkTitle: 'Regulation of immunometabolism by catestatin',
    Email: 'smahata@ucsd.edu ',
    state: 'San Diego',
    Country: 'USA',
    Institute: 'UCSU',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 33,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 1',
    eID: '1-D-2',
    eTitle: undefined,
    firstName: 'Ricardo',
    lastName: 'Borges',
    Role: 'Speaker',
    talkTitle:
      'Chromogranins as the main actor in the accumulation of amines in secretory vesicles',
    Email: 'rborges@ull.es',
    state: 'Tenerife',
    Country: 'Spain',
    Institute: 'University of La Laguna.',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 34,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 1',
    eID: '1-D-3',
    eTitle: undefined,
    firstName: 'Bhavani Shankar',
    lastName: 'Sahu',
    Role: 'SPeaker',
    talkTitle: 'Regulation of immunometabolism by catestatin.',
    Email: 'bhavanisahubioips@gmail.com',
    state: 'New Delhi',
    Country: 'India',
    Institute: 'National Brain Research Centre',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 35,
    Day: '9.19',
    Time: '11:00 - 13:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 1',
    eID: '1-D-4',
    eTitle: undefined,
    firstName: 'Geert van den',
    lastName: 'Boogaart',
    Role: 'Speaker',
    talkTitle:
      'Chromogranin A and its cleavage product Catestatin control gut immune homeostasis and microbial composition',
    Email: 'g.van.den.bogaart@rug.nl',
    state: 'Groningen',
    Country: 'Netherlands',
    Institute:
      'Groningen Biomolecular Sciences and Biotechnology Institute (GBB)',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 37,
    Day: '9.19',
    Time: '13:00 - 14:45',
    Location: 'Princesa Foyer',
    eCategory: 'Lunch and Poster presentation ',
    eID: 'L-PP-1',
    eTitle: 'Lunch and Poster presentation (1st of 3 sessions)',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 38,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa Rooms',
    eCategory: 'Concurent Symposia (CS)',
    eID: 'CS2',
    eTitle: 'Block 2',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 39,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa Rooms',
    eCategory: 'CS block 2',
    eID: '2-A',
    eTitle: 'Peptides at the intersection of emotion and eating',
    firstName: 'Ki',
    lastName: 'Goosens',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'ki.goosens@mssm.edu>',
    state: 'New York',
    Country: 'USA',
    Institute: 'Icahn School of Medicine at Mount Sinai',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 40,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa I',
    eCategory: 'CS block 2',
    eID: '2-A',
    eTitle: undefined,
    firstName: 'Alfonso',
    lastName: 'Abizaid',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'alfonso.abizaidbucio@carleton.ca',
    state: 'Ottawa',
    Country: 'Canada',
    Institute: 'Carleton University',
    professionalRole: 'professor',
    Observation: undefined
  },
  {
    index: 41,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa I',
    eCategory: 'CS block 2',
    eID: '2-A-1',
    eTitle: undefined,
    firstName: 'Scott',
    lastName: 'Kanoski',
    Role: 'Speaker',
    talkTitle:
      'The role of melanin-concentrating hormone on appetitive processes',
    Email: 'kanoski@usc.edu',
    state: 'California',
    Country: 'USA',
    Institute: 'USC',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 42,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa I',
    eCategory: 'CS block 2',
    eID: '2-A-2',
    eTitle: undefined,
    firstName: 'Michelle',
    lastName: 'Chee',
    Role: 'Speaker',
    talkTitle:
      'Conditional deletion of melanin-concentrating hormone receptor 1 from GABAergic neurons increases locomotor activity',
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 43,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa I',
    eCategory: 'CS block 2',
    eID: '2-A-3',
    eTitle: undefined,
    firstName: 'Thomas',
    lastName: 'Kash',
    Role: 'Speaker',
    talkTitle:
      'Nociceptin in binge eating and reward: Central Amygdala Prepronociceptin-Expressing Neurons Mediate Palatable Food Consumption and Reward',
    Email: 'tkash@email.unc.edu',
    state: 'North Carolina',
    Country: 'USA',
    Institute: 'University of North Carolina',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 44,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa I',
    eCategory: 'CS block 2',
    eID: '2-A-4',
    eTitle: undefined,
    firstName: 'Carrie',
    lastName: 'Ferrario',
    Role: 'Speaker',
    talkTitle: 'The role of insulin in reward',
    Email: 'ferrario@umich.edu',
    state: 'Ann Arbor',
    Country: 'USA',
    Institute: 'Dept. Pharmacology, University of Michigan',
    professionalRole: 'Associate Professor',
    Observation: undefined
  },
  {
    index: 45,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa II',
    eCategory: 'CS block 2',
    eID: '2-B',
    eTitle:
      'Limbic neuropeptide modulators of emotion: implications for fear, anxiety, and appetitive behaviors',
    firstName: 'Joanna',
    lastName: 'Dabrowska',
    Role: 'Chair',
    talkTitle: undefined,
    Email: ' joanna.dabrowska@rosalindfranklin.edu',
    state: 'Chicago',
    Country: 'USA',
    Institute: 'Rosalind Franklin University of Medicine and Science,',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 46,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa II',
    eCategory: 'CS block 2',
    eID: '2-B-1',
    eTitle: undefined,
    firstName: 'Joanna',
    lastName: 'Dabrowska',
    Role: 'Speaker',
    talkTitle:
      'Oxytocin receptor transmission facilitates fear memory to predictable threats by inhibiting output neurons of the bed nucleus of the stria terminalis (BNST).',
    Email: ' joanna.dabrowska@rosalindfranklin.edu',
    state: 'Chicago',
    Country: 'USA',
    Institute: 'Rosalind Franklin University of Medicine and Science,',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 47,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa II',
    eCategory: 'CS block 2',
    eID: '2-B-2',
    eTitle: undefined,
    firstName: 'Paul J',
    lastName: 'Marvar',
    Role: 'Speaker',
    talkTitle:
      'A role for angiotensin II in emotional flexibility and fear-based disorders',
    Email: 'pmarvar@gwu.edu',
    state: 'Washington DC',
    Country: 'USA',
    Institute: 'George Washington University,',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 48,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa II',
    eCategory: 'CS block 2',
    eID: '2-B-3',
    eTitle: undefined,
    firstName: 'Raul Andero',
    lastName: 'Gali',
    Role: 'Speaker',
    talkTitle:
      'A drug targeting the peptide Neurokinin B receptor with sex-opposite effects in memory',
    Email: 'raul.andero@uab.cat',
    state: 'Barcelona',
    Country: 'Spain',
    Institute: 'Autonomous University of Barcelona',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 49,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa II',
    eCategory: 'CS block 2',
    eID: '2-B-4',
    eTitle: undefined,
    firstName: 'Zoe Anatasia',
    lastName: 'McElligott',
    Role: 'Speaker',
    talkTitle: 'Neurotensin in reward processes',
    Email: 'zoemce@email.unc.edu ',
    state: 'Chapel Hill',
    Country: 'USA',
    Institute: 'University of North Carolina',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 50,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa III',
    eCategory: 'CS block 2',
    eID: '2-C',
    eTitle: 'Human neuropeptides in health and disease',
    firstName: 'Aimin',
    lastName: 'Bao',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'baoaimin@zju.edu.cn',
    state: 'Hangzhou',
    Country: 'China',
    Institute: 'Zhejiang University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 51,
    Day: '9.19',
    Time: undefined,
    Location: 'Princesa III',
    eCategory: 'CS block 2',
    eID: '2-C',
    eTitle: 'Human neuropeptides in health and disease',
    firstName: 'Dick',
    lastName: 'Swaab',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'd.f.swaab@nin.knaw.nl',
    state: 'Amsterdam',
    Country: 'Netherlands',
    Institute: 'Netherlands Institute for Neuroscience ',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 52,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa III',
    eCategory: 'CS block 2',
    eID: '2-C-1',
    eTitle: undefined,
    firstName: 'Ai-Min',
    lastName: 'Bao',
    Role: 'Speaker',
    talkTitle:
      'Sex differences in hypothalamic neuropeptide systems and depression',
    Email: 'baoaimin@zju.edu.cn',
    state: 'Hangzhou',
    Country: 'China',
    Institute: 'Zhejiang University',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 53,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa III',
    eCategory: 'CS block 2',
    eID: '2-C-2',
    eTitle: undefined,
    firstName: 'Chun-Xia',
    lastName: 'Yi',
    Role: 'Speaker',
    talkTitle: 'Hypothalamic neuron-glial interaction in metabolic disorders',
    Email: 'c.yi@amc.uva.nl',
    state: 'Amsterdam',
    Country: 'Netherlands',
    Institute: 'Academisch Medisch Centrum Universiteit van Amsterdam ',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 54,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa III',
    eCategory: 'CS block 2',
    eID: '2-C-3',
    eTitle: undefined,
    firstName: 'Erik ',
    lastName: 'Hrabovszky',
    Role: 'Speaker',
    talkTitle: 'The Kisspeptin system in reproduction and emotions',
    Email: 'hrabovszky.erik@koki.mta.hu',
    state: 'Budapest',
    Country: 'Hungary',
    Institute:
      'Institute of Experimental Medicine, Hungarian Academy of Sciences',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 55,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa III',
    eCategory: 'CS block 2',
    eID: '2-C-4',
    eTitle: undefined,
    firstName: 'Jing',
    lastName: 'Lu',
    Role: 'Speaker',
    talkTitle: 'Changes of the hypocretin/orexin in schizophrenia',
    Email: 'lujing2016@zju.edu.cn',
    state: 'Hangzhou',
    Country: 'china',
    Institute: 'Zhejiang University',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 56,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 2',
    eID: '2-D',
    eTitle:
      'Integration of homeostasis by the hypothalamo-neurohypophyseal system',
    firstName: 'Andre',
    lastName: 'Mecawi',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'mecawi.as@gmail.com',
    state: 'Sao Paulo',
    Country: 'Brazil',
    Institute: 'Universidade Federal de S\u00e3o Paulo',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 57,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 2',
    eID: '2-D-1',
    eTitle: undefined,
    firstName: 'David',
    lastName: 'Murphy',
    Role: 'Speaker',
    talkTitle: 'Regulation of the supraoptic nucleus by gut peptides',
    Email: 'Murphy@bristol.ac.uk ',
    state: 'Bristol',
    Country: 'UK',
    Institute: 'University of Bristol',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 58,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 2',
    eID: '2-D-2',
    eTitle: undefined,
    firstName: 'Yoichi',
    lastName: 'Ueta',
    Role: 'Speaker',
    talkTitle:
      'Transgenic approaches to reveal physiological role of central vasopressin system',
    Email: 'yoichi@med.uoeh-u.ac.jp',
    state: 'Kitakyushu',
    Country: 'Japan',
    Institute: 'University of Occupational and Environmental Health',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 59,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 2',
    eID: '2-D-3',
    eTitle: undefined,
    firstName: 'Andre',
    lastName: 'Mecawi',
    Role: 'Speaker',
    talkTitle:
      'Estrogen control of hypothalamo-neurohypophyseal gene expression and hormonal secretion',
    Email: 'mecawi.as@gmail.com',
    state: 'Sao Paulo',
    Country: 'Brazil',
    Institute: 'Universidade Federal de S\u00e3o Paulo',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 60,
    Day: '9.19',
    Time: '15:00 - 17:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 2',
    eID: '2-D-4',
    eTitle: undefined,
    firstName: 'Danilo',
    lastName: 'Lustrino',
    Role: 'Speaker',
    talkTitle:
      'Anabolic and Anti-catabolic Effects of Oxytocin on Skeletal Muscle Protein Metabolism',
    Email: 'danilolustrino@gmail.com',
    state: 'Sergipe',
    Country: 'Brazil',
    Institute: 'Federal University of Sergipe',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 61,
    Day: '9.19',
    Time: '17:30 - 18:30',
    Location: 'Atlantes Anfitreater',
    eCategory: 'Plenary',
    eID: 'PL2',
    eTitle: 'Plenary lecture 2',
    firstName: 'Dick',
    lastName: 'Swaab',
    Role: 'Speaker',
    talkTitle: 'Sexual differentiation of the human brain',
    Email: 'd.f.swaab@nin.knaw.nl',
    state: 'Amsterdam',
    Country: 'Netherlands',
    Institute: 'Netherlands Institute for Neuroscience ',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 62,
    Day: '9.19',
    Time: '19:00 - 21:00',
    Location: 'TBC',
    eCategory: 'Social event',
    eID: 'SO-1',
    eTitle:
      'IRPS Council, Program Committee and Distinguished Members Reception (invitations)',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 64,
    Day: '9.20',
    Time: '8:30 - 9:30',
    Location: 'Atlantes Anfitreater',
    eCategory: 'Plenary',
    eID: 'PL3',
    eTitle: 'Plenary lecture 3',
    firstName: 'Baldomero (Toto)',
    lastName: 'Olivera',
    Role: 'Speaker',
    talkTitle:
      'Conus venom peptides: from prey-capture mechanisms to biomedical potential',
    Email: 'olivera@biology.utah.edu',
    state: 'Salt Lake City',
    Country: 'USA',
    Institute: 'The University of Utah',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 65,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa Rooms',
    eCategory: 'Concurent Symposia (CS)',
    eID: 'CS3',
    eTitle: 'Block 3',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 66,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 3',
    eID: '3-A',
    eTitle: 'Body-brain interactions in obesity and diabetes',
    firstName: 'Susanne',
    lastName: 'La Fleur',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 's.e.lafleur@amsterdamumc.nl',
    state: 'Amsterdam',
    Country: 'Netherlands',
    Institute: 'University of Amsterdam',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 67,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 3',
    eID: '3-A-1',
    eTitle: undefined,
    firstName: 'Susanne',
    lastName: 'La Fleur',
    Role: 'Chair',
    talkTitle: 'Neuropeptide Y and the motivation to eat',
    Email: 's.e.lafleur@amsterdamumc.nl',
    state: 'Amsterdam',
    Country: 'Netherlands',
    Institute: 'University of Amsterdam',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 68,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 3',
    eID: '3-A-2',
    eTitle: undefined,
    firstName: 'Michael',
    lastName: 'Krashes',
    Role: 'Speaker',
    talkTitle:
      'High fat food biases hypothalamic and mesolimbic expression of consummatory drives',
    Email: 'michael.krashes@nih.gov',
    state: 'Bethesda',
    Country: 'USA',
    Institute: 'NIH/NIDDK,',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 69,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 3',
    eID: '3-A-3',
    eTitle: undefined,
    firstName: 'Alfonso',
    lastName: 'Abizaid',
    Role: 'Speaker',
    talkTitle: 'Ghrelin in appetitive processing and metabolism',
    Email: 'alfonso.abizaidbucio@carleton.ca',
    state: 'Ottawa',
    Country: 'Canada',
    Institute: 'Carleton University',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 70,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 3',
    eID: '3-A-4',
    eTitle: undefined,
    firstName: 'Luis',
    lastName: 'Paiva',
    Role: 'Speaker',
    talkTitle: 'Oxytocin and insulin signalling',
    Email: 'lpaivam@exseed.ed.ac.uk',
    state: 'Santiago de Chile',
    Country: 'Chile',
    Institute: 'Universidad de Chile',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 71,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 3',
    eID: '3-B',
    eTitle:
      'Ascending peptidergic transmission and modulation of memory, emotion and reward',
    firstName: 'Andrew',
    lastName: 'Gundlach',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'andrew.gundlach@florey.edu.au ',
    state: 'Melbourn',
    Country: 'Australia',
    Institute: 'Florey Institute',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 72,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 3',
    eID: '3-B-1',
    eTitle: undefined,
    firstName: 'Stephanie',
    lastName: 'Caligiuri',
    Role: 'Speaker',
    talkTitle:
      'Medial habenular TCF7L2 and HHIP modulating the breakpoints in nicotine taking behavior and risk for diabetes',
    Email: 'Stephanie.Caligiuri@mssm.edu',
    state: 'New York',
    Country: 'USA',
    Institute: 'Icahn School of Medicine at Mount Sinai',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 73,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 3',
    eID: '3-B-2',
    eTitle: undefined,
    firstName: 'Amber',
    lastName: 'Alhadeff',
    Role: 'Speaker',
    talkTitle: 'Gut signaling effects on hypothalamic and reward circuitry',
    Email: 'amberla@sas.upenn.edu',
    state: 'Philadelphia',
    Country: 'USA',
    Institute: 'University of Pennsylvania',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 74,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 3',
    eID: '3-B-3',
    eTitle: undefined,
    firstName: 'Andrew',
    lastName: 'Gundlach',
    Role: 'Speaker',
    talkTitle:
      'Influence of relaxin-3/GABA neurons in the nucleus incertus on memory, emotion and reward',
    Email: 'andrew.gundlach@florey.edu.au ',
    state: 'Melbourn',
    Country: 'Australia',
    Institute: 'Florey Institute',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 75,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 3',
    eID: '3-B-4',
    eTitle: undefined,
    firstName: 'Rohit',
    lastName: 'Menon',
    Role: 'Speaker',
    talkTitle:
      'Neuropeptide regulation of social fear within the lateral septum',
    Email: 'rohit.menon@ur.de',
    state: 'Regensburg',
    Country: 'Germany',
    Institute: 'University of Regensburg',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 76,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 3',
    eID: '3-C',
    eTitle: 'Neuropeptide actions on the stress response',
    firstName: 'Inga',
    lastName: 'Neumann',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'inga.neumann@ur.de',
    state: 'Regensburg',
    Country: 'Germany',
    Institute: 'University of Regensburg',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 77,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 3',
    eID: '3-C',
    eTitle: 'Neuropeptide actions on the stress response',
    firstName: 'Gil',
    lastName: 'Levkowitz',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'Gil.Levkowitz@weizmann.ac.il',
    state: 'Rehovolt',
    Country: 'Israel',
    Institute: 'Weizmann Institute',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 78,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 3',
    eID: '3-C-1',
    eTitle: undefined,
    firstName: 'Gil',
    lastName: 'Levkowitz',
    Role: 'Speaker',
    talkTitle: 'Peptidergic modulation of stress response in zebrafish',
    Email: 'Gil.Levkowitz@weizmann.ac.il',
    state: 'Rehovolt',
    Country: 'Israel',
    Institute: 'Weizmann Institute',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 79,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 3',
    eID: '3-C-2',
    eTitle: undefined,
    firstName: 'Inga',
    lastName: 'Neumann',
    Role: 'Speaker',
    talkTitle: 'Interactions of oxytocin and the HPA axis',
    Email: 'inga.neumann@ur.de',
    state: 'Regensburg',
    Country: 'Germany',
    Institute: 'University of Regensburg',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 80,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 3',
    eID: '3-C-3',
    eTitle: undefined,
    firstName: 'Jaideep',
    lastName: 'Bains',
    Role: 'Speaker',
    talkTitle: 'Hypothalamic CRH neurons in innate defensive strategies',
    Email: 'jsbains@ucalgary.ca',
    state: 'Calgary',
    Country: 'Canada',
    Institute: 'Hotchkiss Brain Institute',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 81,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 3',
    eID: '3-C-4',
    eTitle: undefined,
    firstName: 'Karl',
    lastName: 'Iremonger',
    Role: 'Speaker',
    talkTitle: 'Neural signatures of stress in the CRH system',
    Email: 'karl.iremonger@otago.ac.nz',
    state: 'Dunnedin ',
    Country: 'New Zealand',
    Institute: 'Otago University',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 82,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 3',
    eID: '3-D',
    eTitle: 'Peptide transmission, stress and the extended amygdala ',
    firstName: 'Lee',
    lastName: 'Eiden',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'eidenl@nih.gov',
    state: 'Bethesda',
    Country: 'USA',
    Institute: 'NIMH, NIH',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 83,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 3',
    eID: '3-D-1',
    eTitle: undefined,
    firstName: 'Will',
    lastName: 'Giardino',
    Role: 'Speaker',
    talkTitle:
      'Extended amygdala neuropeptide circuits driving arousal, affect, and addiction',
    Email: 'willgiar@stanford.edu',
    state: 'Stanford',
    Country: 'USA',
    Institute: 'Stanford University',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 84,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 3',
    eID: '3-D-2',
    eTitle: undefined,
    firstName: 'Valentina',
    lastName: 'Sabino',
    Role: 'Speaker',
    talkTitle:
      'Neuropeptides and Anxiety: Actions of CRH and PACAP in Central Amygdala',
    Email: 'vsabino@bu.edu',
    state: 'Massachusets',
    Country: 'USA',
    Institute: 'Boston University School of Medicine',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 85,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 3',
    eID: '3-D-3',
    eTitle: undefined,
    firstName: 'Sunny Z.',
    lastName: 'Jiang',
    Role: 'Speaker',
    talkTitle:
      'Behavioral significance of conditional ablation of PACAPergic projections from brain stem to amygdala',
    Email: 'zhihong.jiang@nih.gov ',
    state: 'Bethesda',
    Country: 'USA',
    Institute: 'National Institutes of Health',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 86,
    Day: '9.20',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 3',
    eID: '3-D-4',
    eTitle: undefined,
    firstName: 'Sung',
    lastName: 'Han',
    Role: 'Speaker',
    talkTitle:
      'Neuropeptides encode parabrachial nucleus inputs to telecephalic structures that determine behavioral responses to pain and other sensory stimuli',
    Email: 'suh048@ucsd.edu',
    state: 'California',
    Country: 'USA',
    Institute:
      ' Salk Institute\u2019s Clayton Laboratories for Peptide Biology',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 88,
    Day: '9.202',
    Time: '12:00 - 13:30',
    Location: 'Princesa Foyer',
    eCategory: 'Lunch and Poster presentation ',
    eID: 'L-PP-2',
    eTitle: 'Lunch and Poster presentation (2nd of 3 sessions)',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 89,
    Day: '9.202',
    Time: '13:30 - 14:30',
    Location: 'Pincesa VI-VII',
    eCategory: 'Special event',
    eID: 'SE-1',
    eTitle: 'Editors-in-Chief /Editors Luncheon',
    firstName: 'Julian',
    lastName: 'Mercer',
    Role: 'Chair',
    talkTitle: 'Journal of Neuroendocrinology ',
    Email: 'j.mercer@abdn.ac.uk',
    state: 'Aberdeen ',
    Country: 'UK',
    Institute: 'The University of Aberdeen',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 90,
    Day: '9.202',
    Time: '14:30 -',
    Location: undefined,
    eCategory: 'Social event',
    eID: 'SO-2',
    eTitle: 'Social afternoon',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 92,
    Day: '9.202',
    Time: '20:00 - 23:00',
    Location: 'Pierre Bar, Pierre Mundo Imperial',
    eCategory: 'Social event',
    eID: 'SO-3',
    eTitle:
      'Young Investigator/Graduate Students Reception: Let\u2019s dance, RegPep!',
    firstName: 'Vito S.',
    lastName: 'Hern\u00e1ndez',
    Role: 'Host',
    talkTitle: undefined,
    Email: 'no.vito.no@gmail.com',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'UNAM',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 93,
    Day: 'nan',
    Time: undefined,
    Location: undefined,
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Mario A.',
    lastName: 'Zetter',
    Role: 'Host',
    talkTitle: undefined,
    Email: 'zetter.salmon@gmail.com',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'UNAM',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 95,
    Day: '9.21',
    Time: '8:30 - 9:30',
    Location: 'Atlantes Anfitreater',
    eCategory: 'Plenary',
    eID: 'PL4',
    eTitle: 'Plenary lecture 4',
    firstName: 'Valery',
    lastName: 'Grinevich',
    Role: 'Speaker',
    talkTitle:
      'How does a single neuropeptide elicit pleiotropic behavioral and metabolic effects? Oxytocin as an example',
    Email: 'Valery.Grinevich@zi-mannheim.de',
    state: 'Mannheim',
    Country: 'Germany',
    Institute: 'Central Institute for Mental Health, University of Heidelberg',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 96,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa Rooms',
    eCategory: 'Concurent Symposia (CS)',
    eID: 'CS4',
    eTitle: 'Block 4',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 97,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 4',
    eID: '4-A',
    eTitle:
      'From perception to social behavior: vasopressinergic regulation in health and disease ',
    firstName: 'Dora',
    lastName: 'Zelena',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'zelena.dora@koki.mta.hu ',
    state: 'Budapest',
    Country: 'Hungary',
    Institute: 'Institute of Experimental Medicine, Hungary Academy of Science',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 98,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 4',
    eID: '4-A-1',
    eTitle: undefined,
    firstName: 'Mike',
    lastName: 'Ludwig',
    Role: 'Speaker',
    talkTitle: 'Vasopressin in olfactory and visual processing',
    Email: 'mike.ludwig@ed.ac.uk',
    state: 'Edinburgh',
    Country: 'UK',
    Institute: 'Centre for Discovery Brain Sciences, University of Edinburgh',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 99,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 4',
    eID: '4-A-2',
    eTitle: undefined,
    firstName: 'Matthew',
    lastName: 'Paul',
    Role: 'Speaker',
    talkTitle: 'Social development and vasopressin',
    Email: 'mjpaul@buffalo.edu',
    state: 'Buffalo',
    Country: 'USA',
    Institute: 'University of Buffalo',
    professionalRole: 'Associate Professor',
    Observation: undefined
  },
  {
    index: 100,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 4',
    eID: '4-A-3',
    eTitle: undefined,
    firstName: 'Alexa',
    lastName: 'Veenema',
    Role: 'Speaker',
    talkTitle:
      'Sex differences in the juvenile and adult vasopressin system in the regulation of social behavior',
    Email: 'aveenema@msu.edu',
    state: 'East Lansing',
    Country: 'Michigan',
    Institute: 'Michigan State University,',
    professionalRole: 'Associate Professor',
    Observation: undefined
  },
  {
    index: 101,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa I',
    eCategory: 'CS block 4',
    eID: '4-A-4',
    eTitle: undefined,
    firstName: 'Dora',
    lastName: 'Zelena',
    Role: 'Chair',
    talkTitle: 'Vasopressin and sociability in autism and schizophrenia',
    Email: 'zelena.dora@koki.mta.hu ',
    state: 'Budapest',
    Country: 'Hungary',
    Institute: 'Institute of Experimental Medicine, Hungary Academy of Science',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 102,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 4',
    eID: '4-B',
    eTitle: 'Peptides and behavior',
    firstName: 'Arpad',
    lastName: 'Dobolyi',
    Role: 'Co-Chair',
    talkTitle: ' ',
    Email: 'dobolyi.arpad@ttk.elte.hu',
    state: 'Budapest',
    Country: 'Hungary',
    Institute: 'Semmelweis University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 103,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 4',
    eID: '4-B-1',
    eTitle: undefined,
    firstName: 'Ioana',
    lastName: 'Carcea',
    Role: 'Speaker',
    talkTitle:
      'Oxytocin neurons enable social transmission of maternal behaviour',
    Email: 'ic283@njms.rutgers.edu',
    state: 'New Jersey',
    Country: 'USA',
    Institute: 'Rutgers University',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 104,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 4',
    eID: '4-B-2',
    eTitle: undefined,
    firstName: 'Ingrid A',
    lastName: 'Fetter',
    Role: 'Speaker',
    talkTitle: 'The evolution of sociality in ants.',
    Email: ' ifetter@rockefeller.edu ',
    state: 'Cuernavaca',
    Country: 'Mexico',
    Institute: 'IBT',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 105,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 4',
    eID: '4-B-3',
    eTitle: undefined,
    firstName: 'Arpad',
    lastName: 'Dobolyi',
    Role: 'Speaker',
    talkTitle:
      'Thalamic integration of social stimuli regulating parental  behavior and the oxytocin system',
    Email: 'dobolyi.arpad@ttk.elte.hu',
    state: 'Budapest',
    Country: 'Hungary',
    Institute: 'Semmelweis University',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 106,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa II',
    eCategory: 'CS block 4',
    eID: '4-B-4',
    eTitle: undefined,
    firstName: 'Zuoxin',
    lastName: 'Wang',
    Role: 'Speaker',
    talkTitle:
      'Interactions between oxytocin with the HPA axis in social behavior in a monogamous rodent species',
    Email: 'zwang@psy.fsu.edu ',
    state: 'Florida',
    Country: 'USA',
    Institute: 'Florida State University',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 107,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 4',
    eID: '4-C',
    eTitle: 'Peptidergic regulation of nociception and pain',
    firstName: 'Alexandre',
    lastName: 'Charlet',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'acharlet@unistra.fr ',
    state: 'Strasbourg',
    Country: 'France',
    Institute: 'University of Strasbourg',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 108,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 4',
    eID: '4-C-1',
    eTitle: undefined,
    firstName: 'Alexandre',
    lastName: 'Charlet',
    Role: 'Speaker',
    talkTitle: 'Oxytocin-induced astrocytes activation in the central amygdala',
    Email: 'acharlet@unistra.fr ',
    state: 'Strasbourg',
    Country: 'France',
    Institute: 'University of Strasbourg',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 109,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 4',
    eID: '4-C-2',
    eTitle: undefined,
    firstName: 'Marc ',
    lastName: 'Landry',
    Role: 'Speaker',
    talkTitle:
      'Relaxin-mediated basolateral amygdala modulation induces analgesia',
    Email: 'marc.landry@u-bordeaux.fr ',
    state: 'Bordeaux',
    Country: 'France',
    Institute: 'University of Bordeaux, France',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 110,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 4',
    eID: '4-C-3',
    eTitle: undefined,
    firstName: 'Magali',
    lastName: 'Chartier',
    Role: 'Speaker',
    talkTitle: 'New neurotensin analog as relevant analgesic molecules',
    Email: 'Magali.Chartier@USherbrooke.ca',
    state: 'Sherbrooke',
    Country: 'Canada',
    Institute: 'University of Sherbrooke, Canada.',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 111,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa III',
    eCategory: 'CS block 4',
    eID: '4-C-4',
    eTitle: undefined,
    firstName: 'Reza',
    lastName: 'Sharif-Naeni',
    Role: 'Speaker',
    talkTitle:
      'Parvalbumin calcium buffer peptide contribute to spinal integration of nociception.',
    Email: 'reza.sharif@mcgill.ca',
    state: 'Quebec',
    Country: 'Canada',
    Institute: 'McGill University',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 112,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 4',
    eID: '4-D',
    eTitle: 'Brain\u2013body interaction in reproduction ',
    firstName: 'Luis Miguel',
    lastName: 'Garc\u00eda-Segura',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'lmgs@cajal.csic.es ',
    state: 'Madrid',
    Country: 'Spain',
    Institute: 'Cajal Institute',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 113,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 4',
    eID: '4-D',
    eTitle: undefined,
    firstName: 'Geert',
    lastName: 'de Vries',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'devries@gsu.edu',
    state: 'Georgia',
    Country: 'USA',
    Institute: 'Georgia State University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 114,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 4',
    eID: '4-D-1',
    eTitle: undefined,
    firstName: 'Simone',
    lastName: 'Meddle',
    Role: 'Speaker',
    talkTitle: 'Peptides and behavior in birds ',
    Email: 'simone.meddle@roslin.ed.ac.uk ',
    state: 'Edinburgh',
    Country: 'UK',
    Institute: 'University of Edinburgh',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 115,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 4',
    eID: '4-D-2',
    eTitle: undefined,
    firstName: 'Robert',
    lastName: 'Millar',
    Role: 'Speaker',
    talkTitle:
      'Novel analogs of Kisspeptin and Neurokinin B in the interrogation of the HPG axis and as therapeutics',
    Email: 'bob.millar@up.ac.za ',
    state: 'Pretoria',
    Country: 'South Africa',
    Institute: 'University of Pretoria',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 116,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 4',
    eID: '4-D-3',
    eTitle: undefined,
    firstName: 'Geert',
    lastName: 'de Vries',
    Role: 'Speaker',
    talkTitle: 'Gonadal hormones and timing of functional brain development',
    Email: 'devries@gsu.edu',
    state: 'Georgia',
    Country: 'USA',
    Institute: 'Georgia State University',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 117,
    Day: '9.21',
    Time: '10:00 - 12:00',
    Location: 'Princesa IV',
    eCategory: 'CS block 4',
    eID: '4-D-4',
    eTitle: undefined,
    firstName: 'Stephanie',
    lastName: 'Padilla',
    Role: 'Speaker',
    talkTitle:
      'Kisspeptins and their involvement in reproduction and temperature regulation.',
    Email: 'slpadilla@umass.edu',
    state: 'Massachussetts',
    Country: 'USA',
    Institute: 'University of Massachusetts',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 119,
    Day: '9.21',
    Time: '12:00 - 13:30',
    Location: 'Princesa Foyer',
    eCategory: 'Lunch and Poster presentation ',
    eID: 'L-PP-3',
    eTitle: 'Lunch and Poster presentation (3rd of 3 sessions)',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 120,
    Day: '9.21',
    Time: '13:30 - 14:30',
    Location: 'Pincesa VI-VII',
    eCategory: 'Special event',
    eID: 'SE-2',
    eTitle: 'Peptide pioneers Roundtable',
    firstName: 'Robert ',
    lastName: 'Millar',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'bob.millar@up.ac.za ',
    state: 'Pretoria',
    Country: 'South Africa',
    Institute: 'University of Pretoria',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 121,
    Day: '9.21',
    Time: undefined,
    Location: undefined,
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Gareth',
    lastName: 'Leng',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'Gareth.Leng@ed.ac.uk ',
    state: 'Edinburgh',
    Country: 'UK',
    Institute: 'Centre for dicovery Brain Sciences,The University of Edinburgh',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 122,
    Day: '9.21',
    Time: undefined,
    Location: undefined,
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Luis Miguel',
    lastName: 'Garc\u00eda-Segura',
    Role: 'Panel member',
    talkTitle: undefined,
    Email: 'lmgs@cajal.csic.es ',
    state: 'Madrid',
    Country: 'Spain',
    Institute: 'Cajal Institute',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 123,
    Day: '9.21',
    Time: undefined,
    Location: undefined,
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Dick',
    lastName: 'Swaab',
    Role: 'Panel member',
    talkTitle: undefined,
    Email: 'd.f.swaab@nin.knaw.nl',
    state: 'Amsterdam',
    Country: 'Netherlands',
    Institute: 'Netherlands Institute for Neuroscience ',
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 124,
    Day: '9.21',
    Time: undefined,
    Location: undefined,
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Ruud',
    lastName: 'Buijs',
    Role: 'Panel member',
    talkTitle: undefined,
    Email: 'ruudbuijs@gmail.com',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'Instituto de Investigaciones Biom\u00e9dicas, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 125,
    Day: '9.21',
    Time: '15:00 - 18:00',
    Location: 'Atlantes Amphithrer',
    eCategory: 'Special event',
    eID: 'SE-3',
    eTitle: 'IRPS General Asembly',
    firstName: 'Lee E.',
    lastName: 'Eiden',
    Role: 'Co-President',
    talkTitle: 'IRPS Distinguished Members Recognition Ceremony',
    Email: 'eidenl@nih.gov',
    state: 'Bethesda',
    Country: 'USA',
    Institute: 'NIMH-IRP, NIH',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 126,
    Day: '9.21',
    Time: undefined,
    Location: undefined,
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: 'Limei',
    lastName: 'Zhang',
    Role: 'Co-President',
    talkTitle:
      'Executive Report; Councillors, Officers and President-Elect Elections; General Discussion.',
    Email: 'limei@unam.mx',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'Med School, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 127,
    Day: '9.21',
    Time: '19:00 - 22:00',
    Location: 'Sal\u00f3n Diamonte',
    eCategory: 'Social event',
    eID: 'SO-3',
    eTitle: 'Conference banquest',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 129,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa Rooms',
    eCategory: 'Concurent Symposia (CS)',
    eID: 'CS5',
    eTitle: 'Block 5',
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 130,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa I',
    eCategory: 'CS block 5',
    eID: '5-A',
    eTitle: 'The circadian system ',
    firstName: 'Ruud',
    lastName: 'Buijs',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'ruudbuijs@gmail.com',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'Instituto de Investigaciones Biom\u00e9dicas, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 131,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa I',
    eCategory: 'CS block 5',
    eID: '5-A-1',
    eTitle: undefined,
    firstName: 'Ruud',
    lastName: 'Buijs',
    Role: 'Speaker',
    talkTitle:
      'The suprachiasmatic nucleus; a responsive clock regulating homeostasis by daily changing the set points of physiological parameters',
    Email: 'ruudbuijs@gmail.com',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'Instituto de Investigaciones Biom\u00e9dicas, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 132,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa I',
    eCategory: 'CS block 5',
    eID: '5-A-2',
    eTitle: undefined,
    firstName: 'Jeff',
    lastName: 'Jones',
    Role: 'Speaker',
    talkTitle:
      'The importance of VIP signaling for the control of corticosterone secretion (15 min)',
    Email: 'jonesjeffr@wustl.edu',
    state: 'St. Louis',
    Country: 'USA',
    Institute: 'Washington University at St. Louis',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 133,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa I',
    eCategory: 'CS block 5',
    eID: '5-A-3',
    eTitle: undefined,
    firstName: 'Eva',
    lastName: 'Soto',
    Role: 'Speaker',
    talkTitle: undefined,
    Email: 'evasoto28@hotmail.com ',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'Med School, UNAM',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 134,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa I',
    eCategory: 'CS block 5',
    eID: '5-A-4',
    eTitle: undefined,
    firstName: 'Alec ',
    lastName: 'Davidson',
    Role: 'Speaker',
    talkTitle:
      'In vivo single cell calcium changes of vasopressin cells of the SCN',
    Email: 'adavidson@msm.edu',
    state: 'Atlanta',
    Country: 'USA',
    Institute: 'Morehouse School of Medicine',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 135,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa I',
    eCategory: 'CS block 5',
    eID: '5-A-5',
    eTitle: undefined,
    firstName: 'Carolina',
    lastName: 'Escobar',
    Role: 'Speaker',
    talkTitle: 'The importance of circadian rhythms for metabolic health',
    Email: 'escocarolina@gmail.com',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'Med School, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 136,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa II',
    eCategory: 'CS block 5',
    eID: '5-B',
    eTitle:
      'Peptide roles in the neuroimmune system and therapeutic implications',
    firstName: 'Teresa',
    lastName: 'Morales',
    Role: 'Chair',
    talkTitle: undefined,
    Email: 'tere5morales@gmail.com',
    state: 'Queretaro',
    Country: 'Mexico',
    Institute: 'Institute of Neurobiology, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 137,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa II',
    eCategory: 'CS block 5',
    eID: '5-B-1',
    eTitle: undefined,
    firstName: 'Quentin',
    lastName: 'Pittman',
    Role: 'Speaker',
    talkTitle:
      'Toward a better understanding of the central consequences of intestinal inflammation: CRH neurons in the amygdala during colitis',
    Email: 'pittman@ucalgary.ca',
    state: 'Calgary',
    Country: 'Canada',
    Institute: 'University of Calgary',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 138,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa II',
    eCategory: 'CS block 5',
    eID: '5-B-2',
    eTitle: undefined,
    firstName: 'Teresa ',
    lastName: 'Morales',
    Role: 'Speaker',
    talkTitle:
      'Protective actions of prolactin in neurotoxin-hippocampal injury',
    Email: 'tere5morales@gmail.com',
    state: 'Queretaro',
    Country: 'Mexico',
    Institute: 'Institute of Neurobiology, UNAM',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 139,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa II',
    eCategory: 'CS block 5',
    eID: '5-B-3',
    eTitle: undefined,
    firstName: 'Abimael',
    lastName: 'Gonz\u00e1lez-Hern\u00e1ndez',
    Role: 'Speaker',
    talkTitle:
      'The interaction between oxytocin and microglia in spinal pain processing (20 min)',
    Email: 'abimaelgh@gmail.com ',
    state: 'Queretaro',
    Country: 'Mexico',
    Institute: 'Institute of Neurobiology, UNAM',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 140,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa II',
    eCategory: 'CS block 5',
    eID: '5-B-4',
    eTitle: undefined,
    firstName: 'Mario A. ',
    lastName: 'Zetter',
    Role: 'Speaker',
    talkTitle:
      'Early life stress and neuropeptides: microglial as a possible bridge in shaping neurodevelopment (20 min)',
    Email: 'zetter.salmon@gmail.com',
    state: 'Mexico',
    Country: 'Mexico',
    Institute: 'Med School, UNAM',
    professionalRole: 'Young investigator',
    Observation: undefined
  },
  {
    index: 141,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa II',
    eCategory: 'CS block 5',
    eID: '5-B-5',
    eTitle: undefined,
    firstName: 'Andr\u00e9s',
    lastName: 'Quintar-Stephano',
    Role: 'Speaker',
    talkTitle: 'Arginine vasopressin as an immunomodulatory hormone',
    Email: 'aquinta@correo.uaa.mx',
    state: 'Aguas Calientes',
    Country: 'Mexico',
    Institute: 'Universidad of Aguas Calientes',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 142,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa III',
    eCategory: 'CS block 5',
    eID: '5-C',
    eTitle:
      'The cardiovascular brain: The role of the renin angiotensin system and circumventricular organs',
    firstName: 'Thomas',
    lastName: 'Cunningham',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'Tom.Cunningham@unthsc.edu',
    state: 'Dallas',
    Country: 'USA',
    Institute: 'UNT Health Science Center',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 143,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa III',
    eCategory: 'CS block 5',
    eID: '5-C',
    eTitle: undefined,
    firstName: 'Alastair',
    lastName: 'Ferguson',
    Role: 'Co-Chair',
    talkTitle: undefined,
    Email: 'avf@queensu.ca',
    state: 'Kingston, Ontario',
    Country: 'Canada',
    Institute: "Med School, Queen's University",
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 144,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa III',
    eCategory: 'CS block 5',
    eID: '5-C-1',
    eTitle: undefined,
    firstName: 'Curt',
    lastName: 'Sigmund',
    Role: 'Speaker',
    talkTitle: 'Renin angiotensin system finally in the brain?',
    Email: 'csigmund@mcw.edu',
    state: 'Milwaukee',
    Country: 'USA',
    Institute: 'Cardiovascular Center, Medical College of Wisconsin',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 145,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa III',
    eCategory: 'CS block 5',
    eID: '5-C-2',
    eTitle: undefined,
    firstName: 'Thomas',
    lastName: 'Cunningham',
    Role: 'Speaker',
    talkTitle:
      'The brain angiotensin system in neural circuits for hydromineral balance and cardiovascular /metabolic regulation',
    Email: 'Tom.Cunningham@unthsc.edu',
    state: 'Dallas',
    Country: 'USA',
    Institute: 'UNT Health Science Center',
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 146,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa III',
    eCategory: 'CS block 5',
    eID: '5-C-3',
    eTitle: undefined,
    firstName: 'Mario',
    lastName: 'Perello',
    Role: 'Speaker',
    talkTitle: 'Ghrelin signaling from circulation into the brain.',
    Email: 'marioperello@yahoo.com',
    state: 'Buenos Aires',
    Country: 'Argentina',
    Institute: 'Instituto Multidisciplinario de Biolog\u00eda Celular',
    professionalRole: 'Investigador independiente?',
    Observation: undefined
  },
  {
    index: 147,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa III',
    eCategory: 'CS block 5',
    eID: '5-C-4',
    eTitle: undefined,
    firstName: 'Alastair',
    lastName: 'Ferguson',
    Role: 'Speaker',
    talkTitle:
      'Circumventricular Organs as Sensors and Integrators of Circulating Signals Controlling Ingestive Behaviours',
    Email: 'avf@queensu.ca',
    state: 'Kingston, Ontario',
    Country: 'Canada',
    Institute: "Med School, Queen's University",
    professionalRole: 'Professor',
    Observation: undefined
  },
  {
    index: 148,
    Day: '9.22',
    Time: '8:00 - 10:00',
    Location: 'Princesa IV',
    eCategory: 'Special event',
    eID: 'SE-4',
    eTitle:
      'Neuropeptide-liganded GPCRs: Therapeutic Possibilities in Biased and Alternative Signaling In Vivo',
    firstName: 'Lee E.',
    lastName: 'Eiden',
    Role: 'Chair',
    talkTitle:
      'Workshop speakes and titles to be announced (an IUPHAR sponsored event)',
    Email: 'eidenl@nih.gov',
    state: 'Bethesda',
    Country: 'USA',
    Institute: 'NIMH-IRP, NIH',
    professionalRole: 'PI',
    Observation: undefined
  },
  {
    index: 149,
    Day: '9.22',
    Time: '10:00 - 11:00',
    Location: 'Check-out if applicable',
    eCategory: undefined,
    eID: undefined,
    eTitle: undefined,
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 150,
    Day: '9.22',
    Time: '11:00 - 11:30',
    Location: 'Atlantes Amphithrer',
    eCategory: 'Plenary',
    eID: 'PL-5',
    eTitle: 'Neuroscience Special Lecture',
    firstName: 'Xiaoke',
    lastName: 'Chen',
    Role: 'Speaker',
    talkTitle: 'Thalamic control of opioid-associated memory',
    Email: 'xkchen@stanford.edu ',
    state: 'Stanford',
    Country: 'USA',
    Institute: 'Stanford University ',
    professionalRole: 'Associate Professor',
    Observation: undefined
  },
  {
    index: 151,
    Day: '9.22',
    Time: '11:30 - 12:15',
    Location: 'Atlantes Amphithrer',
    eCategory: 'Plenary',
    eID: 'PL-6',
    eTitle: 'Victor Mutt Lecture awardee',
    firstName: 'Diego ',
    lastName: 'Bohorguez',
    Role: 'Speaker',
    talkTitle: 'A gut sense for calories',
    Email: 'diego.bohorquez@duke.edu ',
    state: 'Durham, NC',
    Country: 'USA',
    Institute: 'Duke University',
    professionalRole: 'Assitant Professor',
    Observation: undefined
  },
  {
    index: 152,
    Day: '9.22',
    Time: '12:15 - 12-30',
    Location: 'Atlantes Amphithrer',
    eCategory: 'RegPep2020 closure ceremony',
    eID: undefined,
    eTitle: undefined,
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  },
  {
    index: 153,
    Day: '9.22',
    Time: '12:30 - 13:00',
    Location: 'TBC',
    eCategory: 'Group photo',
    eID: undefined,
    eTitle: undefined,
    firstName: undefined,
    lastName: undefined,
    Role: undefined,
    talkTitle: undefined,
    Email: undefined,
    state: undefined,
    Country: undefined,
    Institute: undefined,
    professionalRole: undefined,
    Observation: undefined
  }
];
